spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: *******
    driver-class-name: com.mysql.jdbc.Driver


#spring:
#  datasource:
#    url: jdbc:oracle:thin:@172.16.135.252:1521/account
#    username: query
#    password: query_on
#    driver-class-name: oracle.jdbc.OracleDriver
